### ISSUE TITLE
toHex functionality 

### ISSUE THREAD

**Issue by rgnter** [WireWhiz/BraneEngine#56]
https://github.com/WireWhiz/BraneEngine/blob/ef3ebe260a3f29f07cac98165288b352b22d3277/src/common/utility/hex.h#L28-L33
What does this `keepLeadingZeroes` mean? I can't see any use for this. I've rewritten this algorithm to use `charconv`,
```cpp
template<typename T>
std::string new_toHex(T num, bool keepLeadingZeros = false) {
    if (num == 0)
        return "0";
    std::array<char, sizeof(T) * 2> view{};
    std::to_chars(
            view.begin(),
            view.end(),
            num,
            16
    );
    return std::move(std::string(view.data(), view.size()));
}
```
I wanna make sure I'm not missing anything before creating a PR. 

For 1 million of random `uint8_t` inputs, on average, the old `toHex` function takes ~21ms and the new one only ~4ms. When dealing with `uint32_t` inputs, the old function takes ~41ms and the new one ~39ms.

**Comment by WireWhiz** [comment]
The keep leading zeros was for when I used to want to store asset ID with a common length. So a hexcode storing a uint32_t of one would look like 00000001 instead of just 1. Not sure if I'm using it anywhere anymore, or if it's needed.

**Comment by rgnter** [comment]
It's used in `database.cpp` for converting byte arrays to hex arrays.

**Comment by WireWhiz** [comment]
Ah ok. I should see about storing the values without a conversion if I can. That's a little bit of extra work that shouldn't be needed
